language: node_js
node_js: node
before_script: chmod 0777 ./node_modules/.bin/mocha
deploy:
  provider: heroku
  api_key:
    secure: VJOiLwZVdxxyXBEjeEd1qs43UJ6cQTUgVeszEpdXS3IEmrkPbQv64WK9CxpyaEam7dwYAxNqbJazw6CwgbHrtNkBD5HmmwsDTlssY2hHcu+uN1fUaGs0sLxw2YHaupps7nhAS0fxum1YvAQOzUqON8WSDYPwN8D6U8vl4iSoRZm7ckgJchO35DU6mLkjo0gWD9COaEQ+YEdRmNX1aIRqenOIbcbTIWGmajsDlXcoJ6qpjs3jrwTGb1EyeOY6rhglz4wH9ZKT4bbEejR58+vGlfecsPK8EGcPuHP9w2boGvkxRGNYp/my+2iktezFSqHm+2YCazADCnb5CYCG6qTThtZ0VvonpExQdlOqGWr3I2BRWAEKz+rbgIglIK8q10FZ08PW5Il+6HUrg4JX86D5sEjTLUiW8wgKwmS1VLGwPhBdtpV+SkOsVlAXK6J6ex23POpJ22ieT+HNLGshRNmEWqJC4TrtQCkjxjKj8e2dHzyuDsGfC283d1bmmm+xGdPpmdZyU3LqKedVlbgYsepzbAD2f/lQkwBOh3/aedDzZUlWRTZo942WsngQQPFhnCZbBqV8ejJoVUZcXP+bC6ZCbEwqJK1MXziY5vcU1yYOzZihPU08B3a6HcQLTlbUPVj6T6e6/30rFLnR0jpBK1ZTDae5pX6cWKmagnUt4xrFVx8=
  app: node-blog-post-api
  on:
    repo: jdkoeppen/node-blog-post-api
